<?php echo $this->renderTabs($this->tabs); ?>

<?php if (count($this->monitors) > 0) { ?>
    <div class="graphLeft">
        <h3 class="center"><?php echo pm_Locale::lmsg('overviewGraphHeading') ?></h3>
        <div id="graph" class="uptimeRobotLastDaysGraph"></div>
        <script>
            require(['//cdn.plot.ly/plotly-latest.min.js'], function (Plotly) {

                var data = <?php echo json_encode($this->chartData) ?>;
                var oneDay = 86400000;
                var twoDays = oneDay * 2;
                var fiveDays = oneDay * 5;
                var tenDays = oneDay * 10;
                var twentyDays = oneDay * 20;

                // Calculate how many labels are drawn on the x-axis
                var dtickX = oneDay;
                if (<?php echo $this->timespan; ?> > 30) {
                    dtickX = twoDays;
                }
                if (<?php echo $this->timespan; ?> > 60) {
                    dtickX = fiveDays;
                }
                if (<?php echo $this->timespan; ?> >= 180) {
                    dtickX = tenDays;
                }
                if (<?php echo $this->timespan; ?> >= 360) {
                    dtickX = twentyDays;
                }

                // Calculate how many labels are drawn on the y-axis
                var maxRange = <?php echo $this->chartMaxRange; ?>;
                var dtickY = 1;
                if(maxRange > 10){
                    dtickY = 2;
                }
                if(maxRange > 20){
                    dtickY = 5;
                }
                if(maxRange > 40){
                    dtickY = 10;
                }

                var layout = {
                    barmode: 'stack',
                    xaxis: {
                        title: '<?php echo pm_Locale::lmsg('overviewGraphLast') ?> <?php echo $this->timespan ?> <?php echo pm_Locale::lmsg('overviewGraphDays') ?>',
                        tickangle: -45,
                        tickmode: 'linear',
                        range: [data[0].x[0],  (data[0].x[data[0].x.length -1] + 1)],
                        tickfont: {
                            size: 9,
                            color: 'black'
                        },
                        dtick: dtickX,
                        type: 'date'
                    },
                    yaxis: {
                        title: '<?php echo pm_Locale::lmsg('overviewGraphOfflineTimes') ?>',
                        tickmode: 'linear',
                        range: [<?php echo $this->chartMinRange ?>, 100.5],
                        dtick: dtickY
                    },
                    margin: {
                        l: 50,
                        r: 50,
                        b: 80,
                        t: 20
                    }
                };

                Plotly.newPlot('graph', data, layout,  {displayModeBar: false, scrollZoom: false});
            });
        </script>
    </div>

    <div class="infoboxRight"> 
        <h3 class="center"><?php echo pm_Locale::lmsg('overviewGlobalUptime') ?></h3>

        <?php if ($this->globalUptimePercentage === false) { ?>
            <div class="c100 p0 center green">
                <span><?php echo pm_Locale::lmsg('overviewGlobalUptimeNA') ?></span>
                <div class="slice"><div class="bar"></div><div class="fill"></div></div>
            </div>
        <?php } else { ?>
            <div class="c100 p<?php echo round($this->globalUptimePercentage) ?> center green">
                <span><?php echo $this->globalUptimePercentage ?>%</span>
                <div class="slice"><div class="bar"></div><div class="fill"></div></div>
            </div>
        <?php } ?>
        <?php if (count($this->monitors) > 0) { ?>
            <p class="center margin">
                <?php echo pm_Locale::lmsg('overviewGlobalUptimeText', ['timespan' => $this->timespan]); ?>
            </p>
            <div class="uptimes">
                <?php foreach($this->monitors as &$monitor) { ?>
                    <div class="uptimesEntry">
                        <?php echo Modules_UptimeRobot_List_Monitors::getHumandReadableURL($monitor->type, $monitor->url) ?>
                        <span class="percentage"><?php 
                            if($monitor->uptime){
                                echo $monitor->uptime[$this->timespan*24].'%'; 
                            } else {
                                echo pm_Locale::lmsg('overviewMonitorStatusPaused');
                            }
                        ?></span>
                    </div>        
                <?php } ?>
            </div>
        <?php } ?>
    </div>

    <br style="clear: both"/>

    <p class="center">
        <?php if ($this->timespan != 7) { ?>
            <a href="./?timespan=7"><?php echo pm_Locale::lmsg('overviewTimespan7') ?></a>
        <?php } else { ?>
            <strong><?php echo pm_Locale::lmsg('overviewTimespan7'); ?></strong>
        <?php } ?>

            | 

        <?php if ($this->timespan != 30) { ?>
            <a href="./?timespan=30"><?php echo pm_Locale::lmsg('overviewTimespan30') ?></a>
        <?php } else { ?>
            <strong><?php echo pm_Locale::lmsg('overviewTimespan30'); ?></strong>
        <?php } ?>

            | 

        <?php if ($this->timespan !=60) { ?>
            <a href="./?timespan=60"><?php echo pm_Locale::lmsg('overviewTimespan60') ?></a>
        <?php } else { ?>
            <strong><?php echo pm_Locale::lmsg('overviewTimespan60'); ?></strong>
        <?php } ?>

            | 

        <?php if ($this->timespan !=180) { ?>
            <a href="./?timespan=180"><?php echo pm_Locale::lmsg('overviewTimespan180') ?></a>
    <?php } else { ?>
            <strong><?php echo pm_Locale::lmsg('overviewTimespan180'); ?></strong>
        <?php } ?>

            | 

            <?php if ($this->timespan !=360) { ?>
            <a href="./?timespan=360"><?php echo pm_Locale::lmsg('overviewTimespan360') ?></a>
        <?php } else { 
            echo pm_Locale::lmsg('overviewTimespan360');
        } ?>
    </p>
<?php } ?>

<h2><?php echo pm_Locale::lmsg('overviewMonitors') ?></h2>
<p><?php echo pm_Locale::lmsg('overviewMonitorsDescription') ?></p>
<p><?php echo $this->renderList($this->monitorsList); ?></p>

<h2><?php echo pm_Locale::lmsg('overviewEvents') ?></h2>
<p><?php echo $this->renderList($this->eventsList); ?></p>

